nodes:
  1:
    host: "0.0.0.0"
    port: 9001
  2:
    host: "0.0.0.0"
    port: 9002
  3: 
    host: "0.0.0.0"
    port: 9003
  4: 
    host: "0.0.0.0"
    port: 9004
  5: 
    host: "0.0.0.0"
    port: 9005